### PR TITLE
Changed upper carbon intensity limit color to dark brown; added missing exchange HR -> RS

### LINKED ISSUE #280: Black color is often interpreted as missing data
I've now heard it quite a few times on Reddit and on the last call I had.
It might be worth switching to a dark red or dark brown color instead of going the whole way to black.

### LINKED ISSUE #281: Missing exchange HR -> RS
pasted_image_at_2017_01_13_11_52_am

### PR DESCRIPTION
**Pull request by Pantkowsky**
Fix #280 and fix #281 

untitled

### CODE REVIEW

**Comment by Pantkowsky** [comment]
The current color for the countries with highest carbon intensity 

untitled

**Comment by ThierryOllivero** [comment]
I see rgb(26,13,0) as black. 

What would it give with "darkbrown" ?

**Comment by Pantkowsky** [comment]
"darkbrown" is not recognized. There is saddlebrown that looks like red.

**Comment by corradio** [comment]
Darkbrown doesn't exist. You see it as black? I really see it as very dark brown, but not black

**Comment by ThierryOllivero** [comment]
Maybe the screen of my phone is not so great. Nevermind. Thank you Adam !

**Pull request merged**
