### PR TITLE
Update tooltip formatting

### PR DESCRIPTION
**Pull request by corradio**
I took a few minutes to update and make more user-friendly the tooltip formatting.

Before:
image

After:
image

### CODE REVIEW

**Comment by ThierryOllivero** [comment]
@corradio : I like it. Do you think you can also use this PR for #283?

**Comment by corradio** [comment]
It requires a bit more coding actually. Easy but less urgent and I thought it could be a good task for someone to get into the code.

**Comment by ThierryOllivero** [comment]
True. Is it really ugly without the <small> balise? I find it kind of small, but I imagine there must be a reason for that.

**Comment by corradio** [comment]
What do you mean by "balise"?

**Comment by ThierryOllivero** [comment]
I forgot to use the code function... I meant the `small` tag

**Comment by brunolajoie** [comment]
I would add total country production here 
image

or be more precise in your tooltip: write "36% of total FR production"

**Pull request merged**
