### PR TITLE
Parser Switzerland

### PR DESCRIPTION
**Pull request by kinemate**
Swiss real-time in/outflows
data source: www.swissgrid.ch

### CODE REVIEW

**Comment by corradio** [comment]
Hello @kinemate ! Thanks for submitting this. Can you dig a bit into the data quality (which production sources are available and what the time lag is)?
A couple of days ago we integrate CH data from ENTSOE. It seems to be quite delayed but we should make sure your parser provides better data :)

**Comment by kinemate** [comment]
Hi @corradio,

Thanks for your comment. 
I have noticed the ENTSOE data for import/export flows to/from Switzerland is often delayed by 1-2 hours. The Swissgrid data is updated every 30sec with a 20min live delay.

Obviously just a minor issue or improvement, so feel free to disregard.

**Comment by corradio** [comment]
This is very relevant in relation to #120. Currently there's an issue where you can't fetch both exchange and production separately, but that could be fixed soon. Is it ok if I reach back to you when this is done?

**Comment by kinemate** [comment]
Sure, makes sense that #120 might actually solve the perceived data staleness.

**Comment by corradio** [comment]
@kinemate if you want to help us with the development, feel free to join http://slack.tmrow.co

**Pull request closed without merging**
