### PR TITLE
Updated cz, de, rs, me capacities

### LINKED ISSUE #372: Capacities of CZ, DE, Montenegro, Serbia
Hallo, at first I would like to thank you for creation of such a wonderful tool as an online actual electriity map. It is great for comparison of the power systems of the countries. 
My Issue: As a citizen of Czech Republic I have double checked the info about it in your system:
I found out the wrong data about total output of power plants in this country, the corect ones are (based on the 2014 annual report of czech energy regulatory office) 
gas power plants: 1363,3MWe
nuclear power plants: 4290 MWe (increased due to higher efficiency of the electricity generator turbines)
hydro power plants: 1080,4 MWe
pumped storage hydro power plants: 1171,5 MWe
wind power plants: 278,1MWe
solar power plants: 2067,4 MWe
"coal" power plants: 10836,7 MWe (in this kind are included also power plants using the rest of fuel types - 4,8% of it is biomass, the "hardcore coal" is approx. 90% of the total power of this type)

### PR DESCRIPTION
**Pull request by brunolajoie**
Fixes #372

### CODE REVIEW

**Comment by ThierryOllivero** [comment]
I'm not sure for Serbia Bruno. You replace the ENTSO-E value by data coming from a 2015 website. How do you know which one is better.

Also, for consistency, sometimes we remove ENTSO-E to use a "local" site, sometimes the opposite. How do we assess which one is better?

**Comment by corradio** [comment]
I agree, the ERU 2015 Yearly Report on the Operation of the Czech Electricity Grid seemed quite solid.
Also, a good practice is to only close the related issue when it has been merged (see https://github.com/blog/1506-closing-issues-via-pull-requests)

**Comment by brunolajoie** [comment]
My rational so far has been to use ENTSOE 2017 capacities whenever no obvious issue where reported, such as 

- production > capacities
- siginificant discrepencies between official reports and ENSTOE data. 
- incomplete ENSTOE datasets for all types of powerplants

and to do so for two reasons: 
1/ To keep open the possibility to then autoupdate capacities as per ENTSOE dataset.
2/ Because ENTSOE data are often more up to date than reports, which lags by 1/2 years all the time;

**Comment by corradio** [comment]
Ok I'll approve this to unblock it. @ThierryOllivero what do you think?

**Comment by ThierryOllivero** [comment]
I still disagree for Serbia. We went from ENTSOE to an old report.

**Comment by brunolajoie** [comment]
@ThierryOllivero I removed ENTSOE data for Serbia because according to @Martin281 on issue #372 , ENTSOE data is wrong as it includes coal power plant that is actually in Montenegro. Do you still reco. to get back to the wrong ENSTOE data?

**Comment by ThierryOllivero** [comment]
Bruno : #372 mentions the coal plant in Kosovo, not Montenegro. And we merged both countries. So Kosovo is now part of Serbia.

**Comment by brunolajoie** [comment]
All right, changes for RS have been made

**Pull request merged**
