### PR TITLE
[Data Science] Add Documentation and requirements

### PR DESCRIPTION
**Pull request by martindaniel4**
## What's the change ? 

- README documentation in the `datascience` section. We can document here our API reference or the python functions we build to play with EM data 
- A `requirements.txt` file that lets you install all dependencies at once

## Reviewers 

@corradio, @brunolajoie

### CODE REVIEW

**Comment by martindaniel4** [comment]
@ThierryOllivero why did you merge master into this branch ? cf - https://github.com/corradio/electricitymap/commit/d1009a762792133ecee04753b5d37d73db79270d

**Comment by ThierryOllivero** [comment]
Because Oli merged some PR, so your branch needed to be updated. No impact on your files.

GitHub was displaying : 

"This branch is out of sync with the base branch.
Changes from the base branch must be synced with this branch before merging."

**Comment by martindaniel4** [comment]
@ThierryOllivero - Please in the future let me rebase my branch in this case. It messes up the flow :) 

Oli was referring to [this branch](https://github.com/corradio/electricitymap/pull/279#issuecomment-272395872). Not this one. 

Also, you do not need to rebase a branch each time a PR is merged. Only when the master and the branch diverged which is not the case here.

**Comment by ThierryOllivero** [comment]
Sure. I only wanted to help because GitHub was showing a warning that it needed to be synchronized. But well noted, in the future I'll let you or @corradio handle it :)

**Comment by martindaniel4** [comment]
cool thanks !

**Pull request merged**
