### PR TITLE
Update Chrome warning with mobile support

### PR DESCRIPTION
**Pull request by corradio**
- Updated with mobile support
- Reduced the amount of text and removed the Chrome install button in favor of a more dominant "continue anyway button". The reasoning is that the system should let people continue anyway, expecting a few glitches.

Before
image
After
image

@guicoelho and @scottlee120 what do you think?

### CODE REVIEW

**Comment by guicoelho** [comment]
Hey!

We initially thought about blocking non-Chrome completely, then we decided to let people continue anyway and now we're even incentivising people to continue without Chrome. 

What's your reasoning? What changed?

From my POV, w/ this solution the message is "The experience won't be great, but we warned you, so it's your responsibility" whereas I think it should be "We don't really think you should use this without Chrome. If you don't have it, here's a very easy link to get it. If you still want to proceed against our recommendation, then click here."

From everyone who clicks the big "Continue" button, some are people who would have dropped off in the previous version, the rest are the ones who would have switched to Chrome but now proceed without it. This means the net effect of this change is bringing back some of the drop-offs (but with a poor experience) + downgrading the experience of the ones who would have used Chrome otherwise.

**Comment by corradio** [comment]
Exactly! The thing that changed is probably my perception that a lot of
people come with Firefox or Edge and can benefit from 99% of the viz (for
example on Firefox it's only flags that are not showing).
So I'd be inclined to relax a bit our recommendation to force Chrome in
order not to have too much dropout.

I also thought about people that would be dropped because the cost of
changing is too high, whereas if we can show them something that looks
promising, they might do the extra effort to switch.

I think a light warning is enough - I feel like we were too tough in our
recommendation. It sounded like the viz would definitely not work on other
browsers.

**Comment by guicoelho** [comment]
I don't see it exactly like that; this being a show-case we should really focus on making sure everyone has a great experience and gets that WOW effect.

I would in general agree that more accessibility is better but, in this case, just because it's a showcase, I think the value of a less-than-perfect experience is low.

**Comment by corradio** [comment]
I've tried to write a table of what's working where. If you believe that
indeed less than perfect is not acceptable we'll act accordingly.

- Internet Explorer: Not working (I think Scott did some more tests and
maybe "something" works)
- Edge: Perfect
- Safari on new Mac OS: Perfect
- Safari on old Mac OS: unusable (laggy)
- Firefox: Flags are not shown. UI a bit less fluid than Chrome but
responsive nevertheless

I'll let you take the decision because I don't have a strong opinion on
this and I believe it's probably not worth spending too much time thinking
about this :)

**Comment by guicoelho** [comment]
Ah, cool - thanks for the summary.

Then probably what makes sense is to have a hard block for IE (really block it, no way to "continue") - and this soft block you suggest for all the others.

I'd also be fine with only the hard block for IE.

What do you think?

**Comment by corradio** [comment]
OK then let's quickly check that fact with @scottlee120 who was the one
that checked for IE.

**Comment by scottlee120** [comment]
Sure, I'll check for IE now - and Edge if I can download it on my PC.

All the best,
Scott

**Comment by scottlee120** [comment]
I can't check for Edge as it's windows 10 only and I only have 7 but actually the latest IE works fine now. The wind patterns display and also country details.

Unless we still have problems on Safari for OS X, it might actually just be fixed now. Can one of you guys check for Safari on El Capitan? I'm running Sierra already and it's fine there if a bit slow. Firefox is also fine on my Mac.

All the best,
Scott

**Comment by corradio** [comment]
Safari El Capitan is too slow to be usable. We should not recommend to
proceed for Safari on El Capitan.

**Comment by corradio** [comment]
@scottlee120 @guicoelho status?

**Comment by guicoelho** [comment]
@corradio I suggest we get this over with and merge. It's not worth the discussion, I'm also fine with the argument "let's keep it as open as possible".

**Comment by corradio** [comment]
ok! I'll let you merge then (and remember to delete the branch)

**Pull request merged**
