### PR TITLE
Country data updates

### LINKED ISSUE #233: Missing import/export for Estonia
Some data about the import and export is missing, in particular for Estonia. The data can be found here:

http://elering.ee/cross-border-physical-flows/

### PR DESCRIPTION
**Pull request by corradio**
- Update EE & RO w/ ENTSOE
- Add missing exchanges for EE (fixes #233)
- Added RS
- Modified how fast arrows blink depending on power flow

@ThierryOllivero @brunolajoie can one of you please review asap?

image
image
image
image

### CODE REVIEW

**Comment by corradio** [comment]
@ThierryOllivero I changed the speed of blinking, not the size. Size is constant.
Actually you have a good point for oil. In https://en.wikipedia.org/wiki/Life-cycle_greenhouse-gas_emissions_of_energy_sources#2014_IPCC.2C_Global_warming_potential_of_selected_electricity_sources I see no mention of oil, although in https://github.com/corradio/electricitymap/blob/master/web/app/co2eq_parameters.js#L9 we consider 650 g/kWh. @brunolajoie do you know what we should do? I don't remember how that number got here - and I don't like it.

**Comment by ThierryOllivero** [comment]
@corradio I had understood that, and I correct my comment : "will people understand the difference of arrows speed, knowing they did not get the colors or the size (and some the direction) in the past?

Let's keep in mind that the map is primary for CO2, not electricity flows. A way too show the difference in volumes would be a nice-to-have, but is not crucial.

**Comment by corradio** [comment]
Point made. It was actually already the case that blinking speed was proportional to power flow. I made it more obvious now. Let's see what people say. I've read quite some comments about the fact it would be nice to have some visual clue about the amount of power exchanged.

**Comment by brunolajoie** [comment]
Thanks thierry for catching this about oil-power plants GHG intensity. Oil shale would be probably higher but not as high as coal, between 650 and 800 in LCA. I will have a deeper look but it's not gonna be an easy catch

**Pull request merged**
